GET http://localhost:3000/films


//get a film with id
###
GET http://localhost:3000/films/2

###
GET http://localhost:3000/films?minimum-duration=140

###
GET http://localhost:3000/films?minimum-duration=1

###
GET http://localhost:3000/films?minimum-duration=151

###
POST http://localhost:3000/films
Content-Type: application/json

{
  "title": "Interstellar",
  "director": "Christopher Nolan",
  "duration": 169,
  "budget": 165000000,
  "description": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
  "imageUrl": "https://example.com/interstellar.jpg"
}


###
//get with letter filter

GET http://localhost:3000/films?start=In

###
//get fims sorted by duration

GET http://localhost:3000/films?sort=duration

###
//delete a movie
DELETE  http://localhost:3000/films/1

###
//patch a movie

PATCH http://localhost:3000/films/1
Content-Type: application/json

{
  "title": "ronaldo better"
}

###
//put a movie
PUT  http://localhost:3000/films/1
Content-Type: application/json

{
  "title": "behind the scenes",
  "director": "me",
  "duration": 365,
  "budget": 165000000,
  "description": " football interview"
}




